spring.application.name=medical_research
spring.application.name=medical-research


spring.datasource.url=jdbc:postgresql://localhost:5432/medical_research
spring.datasource.username=postgres
spring.datasource.password=Abhay@128


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=Q7mN2xV9kL4pR8sT1wY6uI3oP5aD0fG2hJ9cK7zX4bM8nQ6vS1eW3rT5yU9iO2p
wt.expiration=3600000
server.port=8080